-- Servicio IVA: costo y comisión en 0 (línea de ticket / desglose)
insert into public.catalogo_servicios_costos (
  id_servicio,
  orden,
  servicio,
  tipo_servicio,
  costo_base,
  precio_3,
  precio_4,
  precio_5,
  precio_6,
  precio_7,
  precio_8,
  precio_9,
  precio_10,
  precio_11,
  precio_12,
  precio_13,
  precio_14,
  precio_15,
  precio_16,
  precio_17,
  com_1
)
values (
  57,
  37,
  'IVA',
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0
)
on conflict (id_servicio) do update set
  orden         = excluded.orden,
  servicio      = excluded.servicio,
  tipo_servicio = excluded.tipo_servicio,
  costo_base    = excluded.costo_base,
  precio_3      = excluded.precio_3,
  precio_4      = excluded.precio_4,
  precio_5      = excluded.precio_5,
  precio_6      = excluded.precio_6,
  precio_7      = excluded.precio_7,
  precio_8      = excluded.precio_8,
  precio_9      = excluded.precio_9,
  precio_10     = excluded.precio_10,
  precio_11     = excluded.precio_11,
  precio_12     = excluded.precio_12,
  precio_13     = excluded.precio_13,
  precio_14     = excluded.precio_14,
  precio_15     = excluded.precio_15,
  precio_16     = excluded.precio_16,
  precio_17     = excluded.precio_17,
  com_1         = excluded.com_1,
  updated_at    = now();
